media:
  input: public/media
  output: /media

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    format: yaml-frontmatter

    fields:
      - name: title
        label: Título
        type: string

      - name: pubDate
        label: Fecha
        type: date

      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          choices:
            - arte
            - web
            - threejs
            - proceso
            - notas

      - name: image
        label: Imagen
        type: image
        required: false

      - name: video
        label: Video / GIF
        type: file
        required: false

      - name: body
        label: Contenido
        type: rich-text
